"""redesign_team_session_task_models

Revision ID: 156711dd177f
Revises: b2c3d4e5f6g7
Create Date: 2026-06-03 14:03:17.149565
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '156711dd177f'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('assigned_agent_name', sa.String(length=100), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depends_on', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('artifacts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip dropping existing tables/columns that are still needed
    # Keep: task_issues, workspaces, user_tasks, knowledge_chunks embedding/tsv
    # Keep: node_executions foreign keys
    op.add_column('sessions', sa.Column('goal', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('collaboration_mode', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('task_total', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('task_completed', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('progress_percent', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE sessions SET task_total = 0, task_completed = 0, progress_percent = 0.0")
    op.alter_column('sessions', 'task_total', nullable=False)
    op.alter_column('sessions', 'task_completed', nullable=False)
    op.alter_column('sessions', 'progress_percent', nullable=False)
    # Keep existing tasks columns (SOP tasks table)
    op.add_column('team_members', sa.Column('role_name', sa.String(length=100), nullable=True))
    op.add_column('team_members', sa.Column('role_icon', sa.String(length=10), nullable=True))
    op.add_column('team_members', sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('team_members', sa.Column('preferred_model', sa.UUID(), nullable=True))
    op.add_column('team_members', sa.Column('tools', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('team_members', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.add_column('team_members', sa.Column('can_delegate', sa.Boolean(), nullable=True))
    # Migrate data: role_slot -> role_name
    op.execute("UPDATE team_members SET role_name = COALESCE(role_slot, '成员'), role_icon = '🤖', is_required = FALSE, can_delegate = TRUE")
    op.alter_column('team_members', 'role_name', nullable=False)
    op.alter_column('team_members', 'role_icon', nullable=False)
    op.alter_column('team_members', 'is_required', nullable=False)
    op.alter_column('team_members', 'can_delegate', nullable=False)
    op.drop_constraint(op.f('uq_team_role_slot'), 'team_members', type_='unique')
    op.drop_column('team_members', 'role_slot')
    op.add_column('teams', sa.Column('icon', sa.String(length=10), nullable=True))
    op.add_column('teams', sa.Column('collaboration_mode', sa.String(length=20), nullable=True))
    op.add_column('teams', sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('teams', sa.Column('default_tools', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('teams', sa.Column('knowledge_sources', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('teams', sa.Column('allow_agent_to_agent', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('require_hitl_for', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('teams', sa.Column('max_parallel_agents', sa.Integer(), nullable=True))
    # Migrate data: mode -> collaboration_mode, set defaults
    op.execute("UPDATE teams SET collaboration_mode = COALESCE(mode, 'supervisor'), icon = '👥', allow_agent_to_agent = TRUE, max_parallel_agents = 3")
    op.alter_column('teams', 'icon', nullable=False)
    op.alter_column('teams', 'collaboration_mode', nullable=False)
    op.alter_column('teams', 'allow_agent_to_agent', nullable=False)
    op.alter_column('teams', 'max_parallel_agents', nullable=False)
    op.drop_column('teams', 'exec_mode')
    op.drop_column('teams', 'allowed_tools')
    op.drop_column('teams', 'sop_format')
    op.drop_column('teams', 'mode')
    op.drop_index(op.f('idx_workflow_templates_template_type'), table_name='workflow_templates')
    op.create_index('idx_workflow_templates_template_type', 'workflow_templates', ['template_type'], unique=False)
    op.drop_index(op.f('idx_workflows_status'), table_name='workflows')
    op.drop_index(op.f('idx_workflows_template_type'), table_name='workflows')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_workflows_template_type'), 'workflows', ['template_type'], unique=False)
    op.create_index(op.f('idx_workflows_status'), 'workflows', ['status'], unique=False)
    op.drop_index('idx_workflow_templates_template_type', table_name='workflow_templates')
    op.create_index(op.f('idx_workflow_templates_template_type'), 'workflow_templates', ['template_type'], unique=True)
    op.add_column('teams', sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('sop_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('allowed_tools', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('exec_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('teams', 'max_parallel_agents')
    op.drop_column('teams', 'require_hitl_for')
    op.drop_column('teams', 'allow_agent_to_agent')
    op.drop_column('teams', 'knowledge_sources')
    op.drop_column('teams', 'default_tools')
    op.drop_column('teams', 'capabilities')
    op.drop_column('teams', 'collaboration_mode')
    op.drop_column('teams', 'icon')
    op.add_column('team_members', sa.Column('role_slot', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_team_role_slot'), 'team_members', ['team_id', 'role_slot'], postgresql_nulls_not_distinct=False)
    op.drop_column('team_members', 'can_delegate')
    op.drop_column('team_members', 'is_required')
    op.drop_column('team_members', 'tools')
    op.drop_column('team_members', 'preferred_model')
    op.drop_column('team_members', 'capabilities')
    op.drop_column('team_members', 'role_icon')
    op.drop_column('team_members', 'role_name')
    op.add_column('tasks', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tasks_workspace_id_fkey'), 'tasks', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('sessions', 'completed_at')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'progress_percent')
    op.drop_column('sessions', 'task_completed')
    op.drop_column('sessions', 'task_total')
    op.drop_column('sessions', 'collaboration_mode')
    op.drop_column('sessions', 'goal')
    op.create_foreign_key(op.f('node_executions_agent_id_fkey'), 'node_executions', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('node_executions_node_id_fkey'), 'node_executions', 'workflow_nodes', ['node_id'], ['id'], ondelete='SET NULL')
    op.add_column('knowledge_chunks', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, content)", persisted=True), autoincrement=False, nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('tsv_idx'), 'knowledge_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunks_embedding'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('user_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirement', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('workflow_instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'planning'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('planned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ai_plan_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('iteration_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('previous_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='user_tasks_session_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='user_tasks_team_id_fkey'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='user_tasks_workflow_id_fkey'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], name='user_tasks_workflow_instance_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_user_tasks_workflow_id'), 'user_tasks', ['workflow_id'], unique=False)
    op.create_index(op.f('idx_user_tasks_team_id'), 'user_tasks', ['team_id'], unique=False)
    op.create_index(op.f('idx_user_tasks_status'), 'user_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_user_tasks_session_id'), 'user_tasks', ['session_id'], unique=False)
    op.create_index(op.f('idx_user_tasks_instance_id'), 'user_tasks', ['workflow_instance_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('workspaces_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workspaces_pkey'))
    )
    op.create_table('task_issues',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('node_execution_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], name=op.f('task_issues_user_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], name=op.f('task_issues_workflow_instance_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_issues_pkey'))
    )
    op.create_index(op.f('idx_task_issues_user_task_id'), 'task_issues', ['user_task_id'], unique=False)
    op.create_index(op.f('idx_task_issues_status'), 'task_issues', ['status'], unique=False)
    op.create_index(op.f('idx_task_issues_severity'), 'task_issues', ['severity'], unique=False)
    op.create_index(op.f('idx_task_issues_instance_id'), 'task_issues', ['workflow_instance_id'], unique=False)
    op.drop_table('session_tasks')
    # ### end Alembic commands ###
