"""add_workspaces_and_task_fields

Revision ID: 751f5569dd1c
Revises: 221e574d978f
Create Date: 2026-06-02 12:43:08.226493
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '751f5569dd1c'
down_revision: Union[str, None] = '221e574d978f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_index(op.f('ix_chunks_embedding'), table_name='knowledge_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('tsv_idx'), table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_column('knowledge_chunks', 'tsv')
    op.drop_column('knowledge_chunks', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('knowledge_chunks', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, content)", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('tsv_idx'), 'knowledge_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunks_embedding'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_slot', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('team_members_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_members_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_members_pkey')),
    sa.UniqueConstraint('team_id', 'role_slot', name=op.f('uq_team_role_slot'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
