"""add_memories_table

Revision ID: e04fb4ea415a
Revises: ead82db8d084
Create Date: 2026-05-25 21:11:14.820631
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04fb4ea415a'
down_revision: Union[str, None] = 'ead82db8d084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_level_agent', 'memories', ['level', 'agent_id'], unique=False)
    op.create_index('ix_memories_level_team', 'memories', ['level', 'team_id'], unique=False)
    op.create_index('ix_memories_team_agent', 'memories', ['team_id', 'agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_team_agent', table_name='memories')
    op.drop_index('ix_memories_level_team', table_name='memories')
    op.drop_index('ix_memories_level_agent', table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
